# Generated by Django 5.2.8 on 2025-12-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token de Confirmação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmado'),
        ),
    ]
