# Generated by Django 5.2.8 on 2025-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de Confirmação'),
        ),
    ]
