# Generated by Django 5.2.7 on 2025-10-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('seminario', 'Seminário'), ('palestra', 'Palestra'), ('minicurso', 'Minicurso'), ('semana', 'Semana Acadêmica')], max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(verbose_name='Data final')),
                ('time', models.CharField(help_text='Ex.: 14:00 - 18:00', max_length=50, verbose_name='Horário')),
                ('place', models.CharField(max_length=200, verbose_name='Local')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
