# Generated by Django 5.2.8 on 2025-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events_banners/', verbose_name='Banner'),
        ),
    ]
