# Generated by Django 5.2.8 on 2025-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Presença Confirmada'),
        ),
    ]
